### ISSUE TITLE
C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32>python -m pip install discord

### ISSUE THREAD

**Issue by ghost** [Hoixi/HoixiDiscord#1]
Exception:
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 72: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 72: invalid start byte

**Comment by ghost** [comment]
Bu ne aq?

Komut: C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32>python -m pip install discord

**Comment by Hoixi** [comment]
Biraz geç gördüm fakat bu hatayı bende aldım bu hatanın nedeni Python'ı custom kurman veya python kurulu iken Visual Studio ile python kurman olabilir. Python'ı bilgisayardan kaldır setupda aşağıdaki seçeneği seç custom kurma standart olarak kur sorun bende böyle düzelmişti belki sendede işe yarar.
